### ISSUE TITLE
"Float in space" variable not working

### ISSUE THREAD

**Issue by FarmrChuck** [Zygahedron/Parabox-Editor#1]
When I set float in space to 1 on my rootblock, the edges of the level are treated like walls when I should be exiting to the void.

**Comment by FarmrChuck** [comment]
Update: Float in space _does_ work, but only when the box is inside another box, and I have managed to get around the issue by putting my rootblock inside a 1 by 1 block.

**Comment by Zygahedron** [comment]
You can also just put it somewhere in an empty spot in itself or another box, float in space removes it from where it's set to be.
